Add generic density compensation, from Pipe Et al
zaccharieramzi/tfkbnufft pull request #26
Opened 2021-01-14 14:04 UTC by chaithyagr

This PR has the density compensator estimation from pipe and menon

2021-01-14 15:45 UTC, zaccharieramzi requested changes
As discussed can you add in a small unit test?

2021-01-14 16:59 UTC, zaccharieramzi requested changes
suggested a few changes

2021-01-14 16:59 UTC, zaccharieramzi commented on tfkbnufft/tests/mri/dcomp_calc_test.py
> +    return
```suggestion
```

2021-01-14 16:59 UTC, zaccharieramzi commented on tfkbnufft/tests/mri/dcomp_calc_test.py
> +    return
you don't need to bother for the `return`

2021-01-14 16:59 UTC, zaccharieramzi commented on tfkbnufft/mri/dcomp_calc.py
> +        )), 'complex64')
it could be nice to make sure that the returned value has the same dimensionality as `calculate_radial_dcomp_tf`.
```suggestion
        )), 'complex64')
    test_sig = test_sig[0, 0]
```
it would also correspond to the doc

2021-01-14 16:59 UTC, zaccharieramzi commented on tfkbnufft/mri/dcomp_calc.py
> +    operators and k-space trajectory.
```suggestion
    This function uses a nufft hyper parameter dictionary
    and k-space trajectory.
```

2021-01-14 17:09 UTC, chaithyagr commented
All done!

2021-01-14 17:11 UTC, zaccharieramzi commented
Yes I think you just need to then adjust the notebook with the new shape returned by the dcomp

2021-01-15 08:21 UTC, chaithyagr commented
> Yes I think you just need to then adjust the notebook with the new shape returned by the dcomp

Oh shoot yes, done now I guess, missed that

2021-01-15 10:17 UTC, zaccharieramzi requested changes
Let's make sure the scaling is alright as discussed

2021-01-15 14:01 UTC, zaccharieramzi requested changes
I think we are getting there, thanks for bearing with me. A few final tweaks

2021-01-15 14:01 UTC, zaccharieramzi commented on tfkbnufft/tests/mri/dcomp_calc_test.py
> +    tf_dcomp = calculate_density_compensator(interpob, tf_ktraj)
ah I had forgotten about the unit test, it should be failing now ...

```suggestion
	nufftob_back = kbnufft_adjoint(interpob)
    nufftob_forw = kbnufft_forward(interpob)
    tf_dcomp = calculate_density_compensator(interpob, nufftob_forw, nufftob_back, tf_ktraj)
```

2021-01-15 14:01 UTC, zaccharieramzi commented on tfkbnufft/mri/dcomp_calc.py
> +    and k-space trajectory.
While I am at it, might as well:
```suggestion
    This function uses a nufft hyper parameter dictionary, the associated nufft
    operators and k-space trajectory.
```

2021-01-15 15:35 UTC, zaccharieramzi approved these changes

2021-01-15 15:35 UTC, zaccharieramzi commented
@chaithyagr LGTM, thanks for the effort.

2021-01-15 15:35 UTC, merged