Add batching codes in grads
zaccharieramzi/tfkbnufft pull request #40
Opened 2021-07-20 13:03 UTC by chaithyagr

The gradients currently dont support batching. This PR handles allowing batching.

2021-07-20 13:31 UTC, zaccharieramzi commented
@chaithyagr Could you update the unit tests to also have a batch test?

2021-07-20 13:37 UTC, chaithyagr commented
Ahh yes, good idea...

2021-07-21 07:59 UTC, chaithyagr commented
Hold on, converting to draft. Under the new dimensioning rules that I am following this will fail! We need to have a better way to handle batching and even multicoil. For now, I will only support batching with an extra warning. (I dont expect this function to be used in multicoil context)

2021-07-21 09:25 UTC, chaithyagr commented
Ready for review. Codes are fixed now and tests are upto date.

2021-07-21 10:07 UTC, zaccharieramzi requested changes
A few legacies

2021-07-21 10:07 UTC, zaccharieramzi commented on tfkbnufft/kbnufft.py
> +                # dy_dom = tf.math.reduce_sum(dy_dom, axis=1)[None, :]
I think this is a legacy, was it a fix after the tests?

2021-07-21 10:07 UTC, zaccharieramzi commented on tfkbnufft/kbnufft.py
> +                # dy_dom = tf.math.reduce_sum(dy_dom, axis=1)[None, :]
same for adjoint

2021-07-21 10:07 UTC, zaccharieramzi commented on tfkbnufft/nufft/interp_functions.py
> +    y = tf.map_fn(_map_body, [x, tm, om], dtype=x.dtype, parallel_iterations=x.shape[0])
Although I think this is a good idea, this won't work (but silently fail) in graph mode because `x.shape[0]` will be `None`.

The default value for this is 10 (which will be applied right now with `x.shape[0]` being `None`) in graph mode, and in eager mode it will use the correct value.

I think let's keep this enhancement for another PR.

2021-07-21 10:35 UTC, chaithyagr commented on tfkbnufft/nufft/interp_functions.py
> +    y = tf.map_fn(_map_body, [x, tm, om], dtype=x.dtype, parallel_iterations=x.shape[0])
Cool.

2021-07-21 10:37 UTC, chaithyagr commented on tfkbnufft/kbnufft.py
> +                # dy_dom = tf.math.reduce_sum(dy_dom, axis=1)[None, :]
Yes... We had to batch things right.. I will not remove the commented `reduce_sum` now as it could be needed when we work in the case where we send a single trajectory. We will then have to sum out all the gradients on our own.

2021-07-21 10:45 UTC, merged